name: Github CI Pipline testing the html file
on:
  push:
    branches:
            - main
jobs:
    validate:
              runs-on: ubuntu-latest
              streps:
                    -name:checkout repository
                    uses: actions/checkout@v4